# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 03:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('address', models.CharField(max_length=80)),
                ('commandant_phone',
                 models.CharField(
                     blank=True,
                     max_length=17,
                     null=True,
                     validators=[
                         django.core.validators.RegexValidator(
                             message=
                             "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed",
                             regex='^\\+?1?\\d{9,15}$')
                     ])),
            ],
            options={
                'verbose_name': 'Dormitory',
                'verbose_name_plural': 'Dormitories',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('fullname', models.CharField(max_length=90)),
                ('room', models.CharField(blank=True, max_length=5,
                                          null=True)),
                ('phone_number',
                 models.CharField(
                     blank=True,
                     max_length=17,
                     null=True,
                     validators=[
                         django.core.validators.RegexValidator(
                             message=
                             "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed",
                             regex='^\\+?1?\\d{9,15}$')
                     ])),
                ('dormitory',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='services.Dormitory')),
                ('user',
                 models.OneToOneField(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('working_position', models.CharField(max_length=20)),
                ('starts_working_at', models.TimeField(blank=True, null=True)),
                ('ends_working_at', models.TimeField(blank=True, null=True)),
                ('works_on_weekend', models.BooleanField(default=False)),
                ('user',
                 models.OneToOneField(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('description', models.TextField()),
                ('desired_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='services.Staff')),
                ('user',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff request',
                'verbose_name_plural': 'Staff requests',
            },
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_exploitable',
                 models.BooleanField(
                     choices=[(True, 'Exploitable'), (False,
                                                      'Not exploitable')],
                     default=True)),
                ('dormitory',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='services.Dormitory')),
            ],
            options={
                'verbose_name': 'Washing machine',
                'verbose_name_plural': 'Washing machines',
                'ordering': ['-is_exploitable', 'dormitory__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='WashingSchedule',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Washing schedule',
                'verbose_name_plural': 'Washing schedules',
                'ordering': ['date', 'time', 'washing_machine'],
            },
        ),
        migrations.CreateModel(
            name='WashingTime',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Washing time',
                'verbose_name_plural': 'Washing time',
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='washingschedule',
            name='time',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='services.WashingTime'),
        ),
        migrations.AddField(
            model_name='washingschedule',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washingschedule',
            name='washing_machine',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='services.WashingMachine'),
        ),
        migrations.AlterUniqueTogether(
            name='washingschedule',
            unique_together=set([('user', 'date')]),
        ),
    ]
