# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=80)),
                ('commandant_phone',
                 models.CharField(
                     blank=True,
                     max_length=17,
                     null=True,
                     validators=[
                         django.core.validators.RegexValidator(
                             message=
                             "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed",
                             regex='^\\+?1?\\d{9,15}$')
                     ])),
            ],
            options={
                'verbose_name': 'Dormitory',
                'verbose_name_plural': 'Dormitories',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('profile_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='services.Profile')),
                ('working_position', models.CharField(max_length=20)),
                ('starts_working_at', models.TimeField(blank=True, null=True)),
                ('ends_working_at', models.TimeField(blank=True, null=True)),
                ('works_on_weekend', models.BooleanField(default=False)),
            ],
            bases=('services.profile', ),
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('description', models.TextField()),
                ('desired_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='services.Staff')),
                ('user',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_exploitable',
                 models.BooleanField(
                     choices=[(True, 'Exploitable'), (False,
                                                      'Not exploitable')],
                     default=True)),
                ('dormitory',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='services.Dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='WashingSchedule',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('washing_time', models.DateTimeField()),
                ('user',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to=settings.AUTH_USER_MODEL)),
                ('washing_machine',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='services.WashingMachine')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles'
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=
                        "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed",
                        regex='^\\+?1?\\d{9,15}$')
                ]),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dormitory',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='services.Dormitory'),
        ),
    ]
