# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
