# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180603_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrequest',
            options={
                'verbose_name': 'Staff request',
                'verbose_name_plural': 'Staff requests'
            },
        ),
        migrations.AlterModelOptions(
            name='washingmachine',
            options={
                'verbose_name': 'Washing machine',
                'verbose_name_plural': 'Washing machines'
            },
        ),
        migrations.AlterModelOptions(
            name='washingschedule',
            options={
                'verbose_name': 'Washing schedule',
                'verbose_name_plural': 'Washing schedules'
            },
        ),
    ]
