# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180605_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='washingtime',
            options={'ordering': ['time'], 'verbose_name': 'Washing time', 'verbose_name_plural': 'Washing time'},
        ),
    ]
