# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180607_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
    ]
