# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_profile_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='washingschedule',
            options={'ordering': ['date', 'time', 'washing_machine'], 'verbose_name': 'Washing schedule', 'verbose_name_plural': 'Washing schedules'},
        ),
        migrations.AlterUniqueTogether(
            name='washingschedule',
            unique_together=set([('user', 'date')]),
        ),
    ]
